import React, { useContext, useState } from 'react';
import { Helmet } from 'react-helmet-async';
import { ThemeContext } from '../ThemeContext';
import Navbar from '../components/Navbar';
import BookEvent from '../components/Booking/BookEvent';

const Privacy = () => {
    const { darkMode } = useContext(ThemeContext);
    const [modalOpen, setModalOpen] = useState(false); // State to manage modal visibility

    return (
        <div id="privacy" className={`flex justify-center items-center ${darkMode ? 'bg-dark text-white' : 'bg-white text-black'}`}>
            <Helmet>
                <title>Privacy Policy | Zimapeak Marketing</title>
                <meta name="description" content="Privacy Policy for Zimapeak Marketing Inc., describing how we collect, use, and protect your information." />
            </Helmet>

            <Navbar setModalOpen={setModalOpen} />

            <div className='flex flex-col max-w-6xl my-40'>
            <div>
                <h1 className='text-4xl font-bold text-center mb-20'>Privacy Policy</h1>
                <p className='mb-2'>
                    Zimapeak Marketing Inc. is committed to protecting your online privacy. This Privacy Statement explains our views and practices concerning privacy and how they may apply to you as a user of our website.
                </p>

                <p className='mb-2'>
                    Zimapeak Marketing Inc. ("we", "our", or "us") operates the website <a href="http://www.zimapeak.com">www.zimapeak.com</a> (the "Service").
                </p>

                <p className='mb-2'>
                    Zimapeak Marketing Inc. is committed to protecting your online privacy. This Privacy Statement explains our views and practices concerning privacy and how they may apply to you as a user of our website, products, and subscriptions.
                </p>

                <p className='mb-2'>
                    This page informs you of our policies regarding the collection, use, and disclosure of personal data when you use our Service and the choices you have associated with that data.
                </p>

                <p className='mb-2'>
                    We use your data to provide and improve the Service. By using the Service, you agree to the collection and use of information in accordance with this policy. Unless otherwise defined in this Privacy Policy, terms used in this Privacy Policy have the same meanings as in our Terms and Conditions, accessible from <a href="http://www.zimapeak.com">www.zimapeak.com</a>.
                </p>

                <h3>Definitions:</h3>
                <p className='mb-2'>
                    <strong>Service:</strong> Service means the <a href="http://www.zimapeak.com">www.zimapeak.com</a> website operated by Zimapeak Marketing Inc.
                </p>

                <p className='mb-2'>
                    <strong>Personal Data:</strong> Personal Data means data about a living individual who can be identified from those data (or from those and other information either in our possession or likely to come into our possession).
                </p>

                <p className='mb-2'>
                    <strong>Usage Data:</strong> Usage Data is data collected automatically either generated by the use of the Service or from the Service infrastructure itself (for example, the duration of a page visit).
                </p>

                <p className='mb-2'>
                    <strong>Cookies:</strong> Cookies are small pieces of data stored on your device (computer or mobile device).
                </p>

                <p className='mb-2'>
                    <strong>Data Controller:</strong> Data Controller means the natural or legal person who (either alone or jointly or in common with other persons) determines the purposes for which and the manner in which any personal information are, or are to be, processed. For the purpose of this Privacy Policy, we are a Data Controller of your Personal Data.
                </p>

                <p className='mb-2'>
                    <strong>Data Processors (or Service Providers):</strong> Data Processor (or Service Provider) means any natural or legal person who processes the data on behalf of the Data Controller. We may use the services of various Service Providers in order to process your data more effectively.
                </p>

                <p className='mb-2'>
                    <strong>Data Subject (or User):</strong> Data Subject is any living individual who is using our Service and is the subject of Personal Data.
                </p>

                <h3>Information We Collect And Use</h3>

                <p className='mb-2'>
                    We collect several different types of information for various purposes to provide and improve our Service to you.
                </p>
            </div>

            <div>
                <h3>Types of Data Collected</h3>
                <h4>Personal Data</h4>
                <p className='mb-2'>
                    While using our Service, we may ask you to provide us with certain personally identifiable information that can be used to contact or identify you ("Personal Data"). Personally identifiable information may include, but is not limited to:
                </p>
                <ul>
                    <li>First name and last name</li>
                    <li>Email address</li>
                    <li>Phone number</li>
                    <li>Business name</li>
                    <li>Website URL</li>
                    <li>Address, State, Province, ZIP/Postal code, City</li>
                    <li>Any personal data you post on our website</li>
                    <li>Data about how you use our website</li>
                    <li>Technical data such as your IP address, your login data, details about your browser, time zone settings, and other technology on the device you use to access our website</li>
                    <li>Your marketing and communication preferences</li>
                    <li>Any information that you directly provide to us whether through our contact form, over the phone, by email, or otherwise</li>
                    <li>Photographs of you at events</li>
                    <li>Cookies and Usage Data</li>
                </ul>

                <p className='mb-2'>
                    We may use your Personal Data to contact you with newsletters, marketing or promotional materials, and other information that may be of interest to you. You may opt out of receiving any, or all, of these communications from us by following the unsubscribe link or instructions provided in any email we send or by contacting us.
                </p>

                <h4>Usage Data</h4>
                <p className='mb-2'>
                    We may also collect information on how the Service is accessed and used ("Usage Data"). This Usage Data may include information such as your computer’s Internet Protocol address (e.g., IP address), browser type, browser version, the pages of our Service that you visit, the time and date of your visit, the time spent on those pages, unique device identifiers, and other diagnostic data.
                </p>

                <h4>Tracking & Cookies Data</h4>
                <p className='mb-2'>
                    We use cookies and similar tracking technologies to track the activity on our Service and hold certain information.
                </p>
                <p className='mb-2'>
                    Cookies are files with small amount of data which may include an anonymous unique identifier. Cookies are sent to your browser from a website and stored on your device. Tracking technologies also used are beacons, tags, and scripts to collect and track information and to improve and analyze our Service.
                </p>
                <p className='mb-2'>
                    You can instruct your browser to refuse all cookies or to indicate when a cookie is being sent. However, if you do not accept cookies, you may not be able to use some portions of our Service.
                </p>
                <p className='mb-2'>
                    Examples of Cookies we use:
                </p>
                <ul>
                    <li>Session Cookies: We use Session Cookies to operate our Service.</li>
                    <li>Preference Cookies: We use Preference Cookies to remember your preferences and various settings.</li>
                    <li>Security Cookies: We use Security Cookies for security purposes.</li>
                </ul>

                <h3>Use of Data</h3>
                <p className='mb-2'>
                    Zimapeak Marketing Inc. uses the collected data for various purposes:
                </p>
                <ul>
                    <li>To provide and maintain our Service</li>
                    <li>To notify you about changes to our Service</li>
                    <li>To allow you to participate in interactive features of our Service when you choose to do so</li>
                    <li>To provide customer support</li>
                    <li>To gather analysis or valuable information so that we can improve our Service</li>
                    <li>To monitor the usage of our Service</li>
                    <li>To detect, prevent and address technical issues</li>
                    <li>To provide you with news, special offers, and general information about other goods, services, and events which we offer that are similar to those that you have already purchased or enquired about unless you have opted not to receive such information</li>
                </ul>

                <h3>Legal Basis for Processing Personal Data Under General Data Protection Regulation (GDPR)</h3>
                <p className='mb-2'>
                    If you are from the European Economic Area (EEA), Zimapeak Marketing Inc.'s legal basis for collecting and using the personal information described in this Privacy Policy depends on the Personal Data we collect and the specific context in which we collect it.
                </p>
                <p className='mb-2'>
                    Zimapeak Marketing Inc. may process your Personal Data because:
                </p>
                <ul>
                    <li>We need to perform a contract with you</li>
                    <li>You have given us permission to do so</li>
                    <li>The processing is in our legitimate interests and it’s not overridden by your rights</li>
                    <li>For payment processing purposes</li>
                    <li>To comply with the law</li>
                </ul>

                <h3>Retention of Data</h3>
                <p className='mb-2'>
                    Zimapeak Marketing Inc. will retain your Personal Data only for as long as is necessary for the purposes set out in this Privacy Policy. We will retain and use your Personal Data to the extent necessary to comply with our legal obligations (for example, if we are required to retain your data to comply with applicable laws), resolve disputes, and enforce our legal agreements and policies.
                </p>
                <p className='mb-2'>
                    Zimapeak Marketing Inc. will also retain Usage Data for internal analysis purposes. Usage Data is generally retained for a shorter period of time, except when this data is used to strengthen the security or to improve the functionality of our Service, or we are legally obligated to retain this data for longer time periods.
                </p>
            </div>

            <div>
                <h3>Transfer of Data</h3>
                <p className='mb-2'>
                    Your information, including Personal Data, may be transferred to — and maintained on — computers located outside of your state, province, country, or other governmental jurisdiction where the data protection laws may differ than those from your jurisdiction.
                </p>
                <p className='mb-2'>
                    If you are located outside United States and choose to provide information to us, please note that we transfer the data, including Personal Data, to United States and process it there.
                </p>
                <p className='mb-2'>
                    Your consent to this Privacy Policy followed by your submission of such information represents your agreement to that transfer.
                </p>
                <p className='mb-2'>
                    Zimapeak Marketing Inc. will take all steps reasonably necessary to ensure that your data is treated securely and in accordance with this Privacy Policy and no transfer of your Personal Data will take place to an organization or a country unless there are adequate controls in place including the security of your data and other personal information.
                </p>

                <h3>Disclosure of Data</h3>

                <h4>Business Transaction</h4>
                <p className='mb-2'>
                    If Zimapeak Marketing Inc. is involved in a merger, acquisition or asset sale, your Personal Data may be transferred. We will provide notice before your Personal Data is transferred and becomes subject to a different Privacy Policy.
                </p>

                <h4>Disclosure for Law Enforcement</h4>
                <p className='mb-2'>
                    Under certain circumstances, Zimapeak Marketing Inc. may be required to disclose your Personal Data if required to do so by law or in response to valid requests by public authorities (e.g., a court or a government agency).
                </p>

                <h4>Legal Requirements</h4>
                <p className='mb-2'>
                    Zimapeak Marketing Inc. may disclose your Personal Data in the good faith belief that such action is necessary to:
                </p>
                <ul>
                    <li>To comply with a legal obligation</li>
                    <li>To protect and defend the rights or property of Zimapeak Marketing Inc.</li>
                    <li>To prevent or investigate possible wrongdoing in connection with the Service</li>
                    <li>To protect the personal safety of users of the Service or the public</li>
                    <li>To protect against legal liability</li>
                </ul>

                <h3>Security of Data</h3>
                <p className='mb-2'>
                    The security of your data is important to us, but remember that no method of transmission over the Internet, or method of electronic storage is 100% secure. While we strive to use commercially acceptable means to protect your Personal Data, we cannot guarantee its absolute security.
                </p>

                <h3>“Do Not Track” Signals</h3>
                <p className='mb-2'>
                    We do not support Do Not Track (“DNT”). Do Not Track is a preference you can set in your web browser to inform websites that you do not want to be tracked.
                </p>
                <p className='mb-2'>
                    You can enable or disable Do Not Track by visiting the Preferences or Settings page of your web browser.
                </p>

                <h3>Your Data Protection Rights Under General Data Protection Regulation (GDPR)</h3>
                <p className='mb-2'>
                    If you are a resident of the European Economic Area (EEA), you have certain data protection rights. Zimapeak Marketing Inc. aims to take reasonable steps to allow you to correct, amend, delete, or limit the use of your Personal Data.
                </p>
                <p className='mb-2'>
                    If you wish to be informed what Personal Data we hold about you and if you want it to be removed from our systems, please contact us.
                </p>
                <p className='mb-2'>
                    In certain circumstances, you have the following data protection rights:
                </p>
                <ul className='font-bold'>
                    <li className='mb-4'>The right to access, update or to delete the information we have on you.</li>
                    <li className='mb-4'>The right of rectification. You have the right to have your information rectified if that information is inaccurate or incomplete.</li>
                    <li className='mb-4'>The right to object. You have the right to object to our processing of your Personal Data.</li>
                    <li className='mb-4'>The right of restriction. You have the right to request that we restrict the processing of your personal information.</li>
                    <li className='mb-4'>The right to data portability. You have the right to be provided with a copy of the information we have on you in a structured, machine-readable and commonly used format.</li>
                    <li className='mb-4'>The right to withdraw consent. You also have the right to withdraw your consent at any time where Zimapeak Marketing Inc. relied on your consent to process your personal information.</li>
                </ul>
                <p className='mb-2'>
                    Please note that we may ask you to verify your identity before responding to such requests.
                </p>
                <p className='mb-2'>
                    You have the right to complain to a Data Protection Authority about our collection and use of your Personal Data. For more information, please contact your local data protection authority in the European Economic Area (EEA).
                </p>

                <h3>Service Providers</h3>
                <p className='mb-2'>
                    We may employ third party companies and individuals to facilitate our Service ("Service Providers"), to provide the Service on our behalf, to perform Service-related services or to assist us in analyzing how our Service is used.
                </p>
                <p className='mb-2'>
                    These third parties have access to your Personal Data only to perform these tasks on our behalf and are obligated not to disclose or use it for any other purpose.
                </p>

                <h3>Analytics</h3>
                <p className='mb-2'>
                    We may use third-party Service Providers to monitor and analyze the use of our Service.
                </p>
                <p className='mb-2'>
                    <strong>Google Analytics:</strong> Google Analytics is a web analytics service offered by Google that tracks and reports website traffic. Google uses the data collected to track and monitor the use of our Service. This data is shared with other Google services. Google may use the collected data to contextualize and personalize the ads of its own advertising network. You can opt-out of having made your activity on the Service available to Google Analytics by installing the Google Analytics opt-out browser add-on. For more information on the privacy practices of Google, please visit the Google Privacy & Terms web page.
                </p>

                <h3>Behavioral Remarketing</h3>
                <p className='mb-2'>
                    Zimapeak Marketing Inc. uses remarketing services to advertise on third party websites to you after you visited our Service. We and our third-party vendors use cookies to inform, optimize and serve ads based on your past visits to our Service.
                </p>
                <p className='mb-2'>
                    <strong>Google AdWords:</strong> Google AdWords remarketing service is provided by Google Inc. You can opt-out of Google Analytics for Display Advertising and customize the Google Display Network ads by visiting the Google Ads Settings page. Google also recommends installing the Google Analytics Opt-out Browser Add-on.
                </p>
                <p className='mb-2'>
                    <strong>Twitter:</strong> Twitter remarketing service is provided by Twitter Inc. You can opt-out from Twitter's interest-based ads by following their instructions.
                </p>
                <p className='mb-2'>
                    <strong>Facebook:</strong> Facebook remarketing service is provided by Facebook Inc. To opt-out from Facebook's interest-based ads, follow these instructions from Facebook. Facebook adheres to the Self-Regulatory Principles for Online Behavioral Advertising established by the Digital Advertising Alliance.
                </p>

                <h3>Payments</h3>
                <p className='mb-2'>
                    We may provide paid products and/or services within the Service. In that case, we use third-party services for payment processing (e.g., payment processors). We will not store or collect your payment card details. That information is provided directly to our third-party payment processors whose use of your personal information is governed by their Privacy Policy. These payment processors adhere to the standards set by PCI-DSS as managed by the PCI Security Standards Council.
                </p>
                <p className='mb-2'>
                    The payment processors we work with are:
                </p>
                <ul>
                    <li>Vanity</li>
                    <li>NMI</li>
                    <li>PayPal</li>
                </ul>

                <h3>Links to Other Sites</h3>
                <p className='mb-2'>
                    Our Service may contain links to other sites that are not operated by us. If you click on a third-party link, you will be directed to that third party's site. We strongly advise you to review the Privacy Policy of every site you visit.
                </p>
                <p className='mb-2'>
                    We have no control over and assume no responsibility for the content, privacy policies, or practices of any third-party sites or services.
                </p>

                <h3>Children's Privacy</h3>
                <p className='mb-2'>
                    Our Service does not address anyone under the age of 18 ("Children").
                </p>
                <p className='mb-2'>
                    We do not knowingly collect personally identifiable information from anyone under the age of 18. If you are a parent or guardian and you are aware that your child has provided us with Personal Data, please contact us. If we become aware that we have collected Personal Data from children without verification of parental consent, we take steps to remove that information from our servers.
                </p>

                <h3>Changes to This Privacy Policy</h3>
                <p className='mb-2'>
                    We may update our Privacy Policy from time to time. We will notify you of any changes by posting the new Privacy Policy on this page.
                </p>
                <p className='mb-2'>
                    You are advised to review this Privacy Policy periodically for any changes. Changes to this Privacy Policy are effective when they are posted on this page.
                </p>

                <h3>Contact Us</h3>
                <p className='mb-2'>
                    If you would like to: access, correct, amend or delete any personal information we have about you, register a complaint, or simply want more information, contact our Privacy Compliance Officer at <a href="mailto:support@zimapeak.com">support@zimapeak.com</a>.
                </p>
            </div>
            </div>

           


            {modalOpen && (
                <div className="fixed z-20 inset-0 overflow-y-auto">
                    <div className="flex items-center justify-center min-h-screen pt-4 px-4 pb-20 text-center sm:block sm:p-0">
                        <div className="fixed inset-0 transition-opacity" aria-hidden="true">
                            <div className="absolute inset-0 bg-gray-500 opacity-75"></div>
                        </div>
                        <div className="inline-block align-bottom bg-white rounded-lg text-left overflow-hidden shadow-xl transform transition-all sm:my-60 sm:align-middle sm:max-w-2xl sm:w-full">
                            <BookEvent closeModal={() => setModalOpen(false)} />
                        </div>
                    </div>
                </div>
            )}
        </div>
    );
};

export default Privacy;
